//go:notebook
//
// Backfill — the scheduler trick that cuts wait without cutting the line.
//
// A batch scheduler (Slurm, on every HPC cluster) has a queue of jobs, each needing
// some number of nodes for some wall-time, and a fixed pool of nodes to place them on.
// The order it runs them in is *policy*, and the policy you pick changes how long
// everyone waits — on the exact same jobs and the exact same hardware.
//
// The naive policy is **FIFO**: run jobs in arrival order, and if the one at the head
// of the queue doesn't fit yet (it wants more nodes than are free), *everyone waits
// behind it.* A single wide job that can't start blocks a hundred one-node jobs that
// could have — the nodes sit idle, and the queue backs up behind a hole nothing is
// allowed to fill. Every cluster user has watched this happen.
//
// **Backfill** (specifically EASY backfill, the Slurm default) is the fix, and it's
// cleverer than "just reorder": it reserves a start time for the head job so it isn't
// starved, then lets *later* jobs jump ahead into the idle gaps — but only if they
// fit *and finish in time not to delay that reservation.* Small jobs stream into the
// holes a wide job is waiting on; the wide job still starts exactly when it would
// have. Nobody at the front pays for it. That's the property that makes it safe to
// turn on, and the one this notebook makes you watch:
//
//   **the head job starts at the same tick under both policies — backfill only fills
//   the gaps around it.** Median wait drops; the blocking job is not sacrificed.
//
// Drag the load (how many jobs), the pool (how many nodes), and toggle the policy.
// Read the **Gantt chart** the way you read `squeue`: each bar is a job, x is time, its
// height is the nodes it holds. Under FIFO you'll see idle whitespace stacked up
// behind a wide bar; flip to backfill and small bars flow into that whitespace — the
// same jobs, packed.
//
// The mechanism: the schedule is a **pure function of (jobs, nodes, policy)** — place
// every job on a node×time grid and read back its start tick. No Prev[T], no clock,
// no RNG at runtime (the job set is generated by a seeded LCG, so it's byte-identical
// across a policy flip — that identity is the whole experiment). Change the policy and
// the entire schedule recomputes from scratch; scrub freely. WASM-live.

package backfill

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// horizon: the node×time grid is this many ticks wide. Comfortably past any schedule
// the sliders can produce, so nothing spills off the end.
const horizon = 4000

// ---------------------------------------------------------------------------
// Inputs
// ---------------------------------------------------------------------------

// Number of jobs in the queue. More jobs → more contention → the policy matters more.
//
//notebook:slider min=6 max=48 step=1
func jobCount() (jobs int) { return 24 }

// Nodes in the pool. The whole fleet every job competes for; a job wanting more nodes
// than are free has to wait.
//
//notebook:slider min=4 max=16 step=1
func poolNodes() (nodes int) { return 8 }

// Policy: 0 = FIFO (strict arrival order — one wide job blocks the queue behind it),
// 1 = EASY backfill (let small jobs fill the gaps without delaying the head job).
//
//notebook:slider min=0 max=1 step=1
func policyPick() (policy int) { return 1 }

// ---------------------------------------------------------------------------
// Compute (Go) — generate the jobs, then place them. All pure.
// ---------------------------------------------------------------------------

// queue is the deterministic job set: `jobs` jobs from a fixed-seed LCG, so it is
// byte-identical every recompute and — crucially — identical across a policy flip.
// That identity is the experiment: the ONLY thing that changes between the two Gantt
// charts is the placement, never the work. Pure in (jobs, nodes).
func queue(jobs int, nodes int) (work Queue) {
	var s uint32 = 0x01234567 // fixed seed — no clock, no math/rand global
	rnd := func(mod int) int {
		s = s*1664525 + 1013904223
		return int(s>>8) % mod
	}
	js := make([]Job, jobs)
	at := 0
	for i := range js {
		at += rnd(3) // arrivals cluster: 0–2 ticks apart
		w := 1 + rnd(nodes)
		if rnd(4) == 0 {
			w = nodes // ~1 in 4 is a full-width blocker — the jobs that cause the jam
		}
		js[i] = Job{ID: i, Arrive: at, Width: w, Dur: 3 + rnd(12)}
	}
	return Queue{Jobs: js, Nodes: nodes}
}

// schedule places every job on the node×time grid under the chosen policy and returns
// the start tick of each, plus the wait-time metrics. Pure in (work, policy): a job's
// start is read off where it lands on the grid, so waits are REAL (start − arrival),
// never assumed. FIFO gates the queue in arrival order (head-of-line blocking); EASY
// backfill reserves the head's earliest slot and lets later jobs that fit sooner run
// ahead — never past the head's reservation.
func schedule(work Queue, policy int) (plan Plan) {
	nodes := work.Nodes
	free := make([]int, horizon)
	for t := range free {
		free[t] = nodes
	}
	start := make([]int, len(work.Jobs))

	// canFit / earliest / place operate on the running free-grid.
	canFit := func(j Job, at int) bool {
		for t := at; t < at+j.Dur && t < horizon; t++ {
			if free[t] < j.Width {
				return false
			}
		}
		return true
	}
	earliest := func(j Job) int {
		for at := j.Arrive; at < horizon; at++ {
			if canFit(j, at) {
				return at
			}
		}
		return horizon - 1
	}
	place := func(j Job, at int) {
		for t := at; t < at+j.Dur && t < horizon; t++ {
			free[t] -= j.Width
		}
		start[j.ID] = at
	}

	// queue order: by arrival, ties by ID (stable, deterministic).
	order := make([]Job, len(work.Jobs))
	copy(order, work.Jobs)
	sort.Slice(order, func(a, b int) bool {
		if order[a].Arrive != order[b].Arrive {
			return order[a].Arrive < order[b].Arrive
		}
		return order[a].ID < order[b].ID
	})

	if policy == 0 {
		// FIFO with head-of-line blocking: a job may not start before any job ahead
		// of it in the queue. `gate` is the running max of placed starts — the queue
		// can't overtake its own head, so a wide job that waits stalls everyone.
		gate := 0
		for _, j := range order {
			at := j.Arrive
			if at < gate {
				at = gate
			}
			for !canFit(j, at) {
				at++
			}
			place(j, at)
			if at > gate {
				gate = at
			}
		}
	} else {
		// EASY backfill: repeatedly take the head, reserve its earliest slot, then let
		// any remaining job whose own earliest slot is no later than the head's run
		// ahead. Because a backfilled job fits at a tick ≤ the head's start, it never
		// pushes the head's reservation out — the safety guarantee.
		pending := order
		for len(pending) > 0 {
			head := pending[0]
			hAt := earliest(head)
			place(head, hAt)
			var still []Job
			for _, j := range pending[1:] {
				if earliest(j) <= hAt {
					place(j, earliest(j))
				} else {
					still = append(still, j)
				}
			}
			pending = still
		}
	}

	waits := make([]int, len(work.Jobs))
	makespan := 0
	for _, j := range work.Jobs {
		waits[j.ID] = start[j.ID] - j.Arrive
		if end := start[j.ID] + j.Dur; end > makespan {
			makespan = end
		}
	}
	return Plan{
		Jobs: work.Jobs, Nodes: nodes, Start: start,
		MedianWait: medianInt(waits),
		MeanWait:   meanInt(waits),
		MaxWait:    maxInt(waits),
		Makespan:   makespan,
	}
}

// ---------------------------------------------------------------------------
// Views
// ---------------------------------------------------------------------------

// The Gantt chart: one bar per job on a node×time grid — x is when it runs, height is
// the nodes it holds, color marks the widest (blocking) jobs. Read it like `squeue`:
// under FIFO, idle whitespace stacks behind a wide bar nothing may pass; under
// backfill, small bars flow into that whitespace. Same jobs, different packing.
//
//notebook:height=440
func gantt(plan Plan) (chart Gantt) {
	return Gantt{Plan: plan}
}

// The verdict: the wait-time numbers the policy trades on. Median wait is the headline
// — flip the policy and watch it move on an unchanged job set.
func stats(plan Plan) (report Readout) {
	return Readout{Cards: []Card{
		{Label: "median wait", Value: f1(plan.MedianWait) + " ticks", Caption: "the headline — halved by backfill on the same jobs"},
		{Label: "mean wait", Value: f1(plan.MeanWait) + " ticks", Caption: "the long tail behind a blocked queue"},
		{Label: "makespan", Value: strconv.Itoa(plan.Makespan) + " ticks", Caption: "when the last job finishes — tighter packing, sooner"},
	}}
}

// Backfill — the scheduler trick that cuts wait without cutting the line.
func intro() (md Markdown) {
	return `A batch scheduler runs a queue of jobs on a fixed pool of nodes, and the
*order* is policy. Under **FIFO**, one wide job that can't fit yet blocks everyone
behind it — nodes sit idle behind a hole nothing may fill. **EASY backfill** reserves
the head job's start time, then lets small jobs jump into the idle gaps *without
delaying that reservation.*

Toggle the policy and read the **Gantt chart** like ` + "`squeue`" + `: the wide
blocking bar starts at the **same tick** either way — backfill only fills the
whitespace around it, so median wait drops and nobody at the front pays. The schedule
is a pure function of (jobs, nodes, policy) — same seeded job set both ways, so the
only thing that changes is the packing. Scrub freely; it recomputes from scratch.`
}

// ===========================================================================
// Metrics
// ===========================================================================

func medianInt(xs []int) float64 {
	if len(xs) == 0 {
		return 0
	}
	s := append([]int(nil), xs...)
	sort.Ints(s)
	n := len(s)
	if n%2 == 1 {
		return float64(s[n/2])
	}
	return float64(s[n/2-1]+s[n/2]) / 2
}

func meanInt(xs []int) float64 {
	if len(xs) == 0 {
		return 0
	}
	sum := 0
	for _, x := range xs {
		sum += x
	}
	return float64(sum) / float64(len(xs))
}

func maxInt(xs []int) int {
	m := 0
	for _, x := range xs {
		if x > m {
			m = x
		}
	}
	return m
}

// ===========================================================================
// Helpers
// ===========================================================================

func f1(v float64) string { return strconv.FormatFloat(v, 'f', 1, 64) }

func esc(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;")
	return r.Replace(s)
}

// ===========================================================================
// Types
// ===========================================================================

// Job is one unit of work: it arrives at a tick, needs Width nodes for Dur ticks.
type Job struct {
	ID, Arrive, Width, Dur int
}

// Queue is the generated job set plus the pool size it competes for.
type Queue struct {
	Jobs  []Job
	Nodes int
}

// Plan is a placed schedule: the start tick of every job (by ID) plus wait metrics.
type Plan struct {
	Jobs       []Job
	Nodes      int
	Start      []int
	MedianWait float64
	MeanWait   float64
	MaxWait    int
	Makespan   int
}

// Gantt draws the placed schedule as bars on a node×time grid.
type Gantt struct{ Plan Plan }

func (g Gantt) Render() Rendered {
	p := g.Plan
	const w, h, pad = 720.0, 440.0, 40.0
	span := p.Makespan
	if span < 1 {
		span = 1
	}
	plotW, plotH := w-2*pad, h-2*pad
	sx := func(t int) float64 { return pad + float64(t)/float64(span)*plotW }
	// vertical: stack node-rows; a job of Width w occupies w adjacent rows.
	rowH := plotH / float64(p.Nodes)

	var b strings.Builder
	fmt.Fprintf(&b, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %.0f %.0f">`, w, h)
	fmt.Fprintf(&b, `<rect width="%.0f" height="%.0f" fill="#fff"/>`, w, h)
	fmt.Fprintf(&b, `<rect x="%.0f" y="%.0f" width="%.0f" height="%.0f" fill="#e7ebf0" stroke="#e7ebf0"/>`,
		pad, pad, plotW, plotH)

	// node gridlines
	for n := 0; n <= p.Nodes; n++ {
		y := pad + float64(n)*rowH
		fmt.Fprintf(&b, `<line x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f" stroke="#e7ebf0"/>`, pad, y, w-pad, y)
	}

	// Place bars greedily onto free node-rows over each job's [start, start+dur). We
	// re-derive row occupancy here purely for drawing (the schedule already guaranteed
	// capacity); this just assigns each job to specific rows so bars don't overlap.
	rowFree := make([][]bool, p.Nodes)
	for r := range rowFree {
		rowFree[r] = make([]bool, span+1)
		for t := range rowFree[r] {
			rowFree[r][t] = true
		}
	}
	// draw in start order for stable, readable stacking.
	order := append([]Job(nil), p.Jobs...)
	sort.Slice(order, func(a, bb int) bool {
		if p.Start[order[a].ID] != p.Start[order[bb].ID] {
			return p.Start[order[a].ID] < p.Start[order[bb].ID]
		}
		return order[a].ID < order[bb].ID
	})
	for _, j := range order {
		st := p.Start[j.ID]
		// find the lowest run of j.Width contiguous rows free across the job's span.
		base := -1
		for r := 0; r+j.Width <= p.Nodes; r++ {
			ok := true
			for rr := r; rr < r+j.Width && ok; rr++ {
				for t := st; t < st+j.Dur && t <= span; t++ {
					if !rowFree[rr][t] {
						ok = false
						break
					}
				}
			}
			if ok {
				base = r
				break
			}
		}
		if base < 0 {
			base = 0 // shouldn't happen; capacity was guaranteed
		}
		for rr := base; rr < base+j.Width; rr++ {
			for t := st; t < st+j.Dur && t <= span; t++ {
				rowFree[rr][t] = false
			}
		}
		x0, x1 := sx(st), sx(st+j.Dur)
		y0 := pad + float64(base)*rowH
		bh := float64(j.Width) * rowH
		// color: wide (blocking) jobs stand out; narrow jobs muted.
		fill := "#2a78d6"
		if j.Width >= p.Nodes {
			fill = "#d03b3b" // full-width blocker
		} else if float64(j.Width) >= float64(p.Nodes)*0.6 {
			fill = "#fab219" // wide
		}
		fmt.Fprintf(&b, `<rect x="%.1f" y="%.1f" width="%.1f" height="%.1f" rx="2" fill=%q stroke="#fff" stroke-width="0.7"/>`,
			x0, y0+1, x1-x0, bh-2, fill)
	}

	fmt.Fprintf(&b, `<text x="%.0f" y="24" font-family="sans-serif" font-size="12" fill="#1b3a6b">Gantt — jobs on the node×time grid (height = nodes held, red = full-width blocker)</text>`, pad)
	fmt.Fprintf(&b, `<text x="%.1f" y="%.1f" font-family="sans-serif" font-size="10" fill="#5b6472">time →</text>`, w-pad-46, h-pad+22)
	fmt.Fprintf(&b, `<text x="%.1f" y="%.1f" font-family="sans-serif" font-size="10" fill="#5b6472" transform="rotate(-90 %.1f %.1f)">nodes</text>`,
		float64(14), pad+plotH/2, float64(14), pad+plotH/2)
	b.WriteString(`</svg>`)
	return Rendered{MIME: "image/svg+xml", Data: b.String()}
}

type Card struct{ Label, Value, Caption string }
type Readout struct{ Cards []Card }

// Render draws the stats as a row of labeled cards. A composite value with no Render
// method carries no MIME and the client leaves the cell hidden — so the cards render
// themselves. Engine-called, not a cell, so fmt here is fine.
func (r Readout) Render() Rendered {
	var b strings.Builder
	b.WriteString(`<div style="display:flex;gap:16px;flex-wrap:wrap">`)
	for _, c := range r.Cards {
		b.WriteString(`<div style="flex:1;min-width:160px;border:1px solid #e7ebf0;border-radius:8px;padding:12px 14px">`)
		fmt.Fprintf(&b, `<div style="font-size:12px;color:#5b6472">%s</div>`, esc(c.Label))
		fmt.Fprintf(&b, `<div style="font-size:24px;font-weight:700;color:#1b3a6b;margin:2px 0">%s</div>`, esc(c.Value))
		if c.Caption != "" {
			fmt.Fprintf(&b, `<div style="font-size:11px;color:#5b6472">%s</div>`, esc(c.Caption))
		}
		b.WriteString(`</div>`)
	}
	b.WriteString(`</div>`)
	return Rendered{MIME: "text/html", Data: b.String()}
}

type Rendered struct{ MIME, Data string }

type Markdown string

func (m Markdown) Render() Rendered { return Rendered{"text/markdown", string(m)} }
