//go:notebook
//
// Cache policy — the best eviction rule depends on the workload, and here's the proof.
//
// You have a cache that holds N items and a stream of accesses that wants more than N.
// When it's full and a miss comes in, something has to go — and the rule you pick for
// *what goes* is the eviction policy. The two classics:
//
//   - **LRU** (least-recently-used) evicts whatever hasn't been touched in the longest
//     time. It bets on **recency**: what you used lately, you'll use again.
//   - **LFU** (least-frequently-used) evicts whatever has been touched the fewest
//     times. It bets on **popularity**: what's been hot stays hot.
//
// "Which is better?" is the wrong question — it has no answer without the workload,
// and this notebook exists to make that concrete. Flip the **workload** toggle:
//
//   - a **working-set** stream (locality — a moving window of hot keys) is a recency
//     workload, and **LRU wins at every cache size**. Watch its hit-rate curve: it
//     *cliffs* upward the moment the cache is big enough to hold the working set, then
//     goes flat — more cache buys nothing once the set fits. That plateau is the
//     answer to "is 2× the cache worth it?": past the cliff, no.
//   - a **Zipf** stream (a few globally-popular keys dominate) is a popularity
//     workload, and **LFU wins at every cache size** — it keeps the hot keys that LRU
//     keeps aging out.
//
// Same two policies, opposite winners, decided entirely by the shape of the traffic.
// The chart plots hit-rate against cache size for BOTH policies at once, so you see
// them cross (or not) and find the knee.
//
// The mechanism: each policy is run over the **whole access stream to a fixed
// horizon inside one cell** — a pure function of (workload, size, stream length).
// The stream is generated by a seeded LCG, so it's byte-identical across a policy
// comparison and reproducible under a scrub; the hit-rates come from actually
// replaying it, not a formula. Same fixed-horizon-pure shape as the PID and n-body
// notebooks. WASM-live.
//
// DEFERRED, honestly (the taxi pattern): #109 framed this over a 100M-line production
// trace streamed out-of-core via a Rel[Access] handle. That out-of-core delivery is a
// separate claim from the teaching, and it lives with taxi/queue in the batch bucket.
// Here the stream is an in-memory synthetic one; everything about the policy lesson is
// real, the scale is not what's being shown.

package cachepolicy

import (
	"fmt"
	"strconv"
	"strings"
)

const (
	streamLen = 6000 // accesses replayed per policy (the fixed horizon)
	universe  = 300  // distinct keys the stream can reference
)

// ---------------------------------------------------------------------------
// Inputs
// ---------------------------------------------------------------------------

// Workload: 0 = working-set (locality — a moving window of hot keys, a recency
// workload), 1 = Zipf (a few globally-popular keys dominate, a popularity workload).
// This is the toggle that flips which policy wins.
//
//notebook:slider min=0 max=1 step=1
func workloadPick() (workload int) { return 0 }

// Cache size — items held before eviction kicks in. The marker line on the chart; the
// curves are swept across all sizes, this picks the one the verdict reports.
//
//notebook:slider min=5 max=200 step=5
func cacheSize() (size int) { return 50 }

// Working-set size — how many keys are "hot" at once in the working-set workload (the
// window that drifts through the key space). LRU's hit-rate cliffs when the cache
// crosses this. Ignored by the Zipf workload.
//
//notebook:slider min=10 max=120 step=5
func workingSetSize() (ws int) { return 50 }

// ---------------------------------------------------------------------------
// Compute (Go) — generate the stream, replay both policies across all sizes.
// ---------------------------------------------------------------------------

// stream is the deterministic access trace for the chosen workload: `streamLen`
// references from a fixed-seed LCG, so it's byte-identical every recompute and across
// a policy comparison (that identity is the experiment — only the policy differs).
// Pure in (workload, ws).
func stream(workload int, ws int) (trace Trace) {
	refs := make([]int, streamLen)
	var s uint32 = 0x00ABCDEF // fixed seed — no clock, no math/rand global
	rnd := func(mod int) int {
		s = s*1664525 + 1013904223
		if mod <= 0 {
			return 0
		}
		return int(s>>8) % mod
	}
	if workload == 0 {
		// working set: strong locality within a window that drifts slowly, so LRU has
		// a sharp cliff when the cache can finally hold the window.
		base := 0
		for i := range refs {
			if rnd(60) == 0 {
				base = (base + ws/3) % universe // window drifts occasionally
			}
			refs[i] = (base + rnd(ws)) % universe
		}
	} else {
		// Zipf-ish: bias toward low-numbered keys (min of several draws), so a handful
		// of keys are globally hot — popularity, which rewards LFU.
		for i := range refs {
			v := rnd(universe)
			for k := 0; k < 4; k++ {
				if w := rnd(universe); w < v {
					v = w
				}
			}
			refs[i] = v
		}
	}
	return Trace{Refs: refs, Workload: workload}
}

// curves replays BOTH policies over the whole stream at every cache size, returning
// the two hit-rate curves. Pure in (trace): the hit-rate at each size comes from
// actually running the eviction rule over the references, never a closed form — so the
// crossing point and the cliff are earned, not assumed.
func curves(trace Trace) (result Curves) {
	sizes := make([]int, 0, universe/5)
	for c := 5; c <= universe; c += 5 {
		sizes = append(sizes, c)
	}
	lru := make([]float64, len(sizes))
	lfu := make([]float64, len(sizes))
	for i, c := range sizes {
		lru[i] = hitRateLRU(trace.Refs, c)
		lfu[i] = hitRateLFU(trace.Refs, c)
	}
	return Curves{Sizes: sizes, LRU: lru, LFU: lfu, Workload: trace.Workload}
}

// ---------------------------------------------------------------------------
// Views
// ---------------------------------------------------------------------------

// The hit-rate curves: LRU and LFU plotted against cache size for the chosen workload,
// with a marker at the selected size. Watch them cross (or not) — the winner is a
// property of the workload, and the knee is the answer to "is more cache worth it?".
//
//notebook:height=400
func rateChart(result Curves, size int) (chart Chart) {
	return Chart{Curves: result, Marker: size}
}

// The verdict at the selected cache size: each policy's hit-rate and which one wins on
// this workload. Flip the workload toggle and watch the winner change.
func verdict(result Curves, size int, workload int) (report Readout) {
	lru, lfu := at(result.Sizes, result.LRU, size), at(result.Sizes, result.LFU, size)
	winner := "tie"
	switch {
	case lru > lfu+0.005:
		winner = "LRU (recency)"
	case lfu > lru+0.005:
		winner = "LFU (popularity)"
	}
	wl := "working-set (locality)"
	if workload == 1 {
		wl = "Zipf (popularity)"
	}
	return Readout{Cards: []Card{
		{Label: "workload", Value: wl, Caption: "the traffic shape decides everything"},
		{Label: "LRU hit-rate", Value: pct(lru), Caption: "keeps what you touched recently"},
		{Label: "LFU hit-rate", Value: pct(lfu), Caption: "keeps what you touch often"},
		{Label: "winner @ size " + strconv.Itoa(size), Value: winner, Caption: "flip the workload — the winner flips too"},
	}}
}

// Cache policy — the best eviction rule depends on the workload, and here's the proof.
func intro() (md Markdown) {
	return `A full cache must evict something on a miss, and the rule is the *policy*.
**LRU** bets on recency (drop the least-recently-used); **LFU** bets on popularity
(drop the least-frequently-used). Which wins? **It depends on the workload** — that's
the whole lesson.

Flip the **workload** toggle: a **working-set** stream (a drifting window of hot keys)
is recency traffic and **LRU wins** — its curve *cliffs* up when the cache fits the
set, then flatlines (more cache buys nothing). A **Zipf** stream (a few keys globally
hot) is popularity traffic and **LFU wins**. Same policies, opposite winners.

Each policy is replayed over the whole access stream to a fixed horizon in one cell —
pure in (workload, size), seeded stream, so the crossing point is earned by running
it, not a formula. Scrub freely.`
}

// ===========================================================================
// Policies — replayed over the reference stream, hit-rate returned.
// ===========================================================================

// hitRateLRU replays the stream through an LRU cache of the given capacity and returns
// the fraction of accesses that hit. Recency order is an MRU-at-end slice.
func hitRateLRU(refs []int, capacity int) float64 {
	if capacity <= 0 {
		return 0
	}
	order := make([]int, 0, capacity) // LRU at front, MRU at end
	in := make(map[int]bool, capacity)
	hits := 0
	for _, k := range refs {
		if in[k] {
			hits++
			for i, x := range order {
				if x == k {
					order = append(order[:i], order[i+1:]...)
					break
				}
			}
			order = append(order, k)
			continue
		}
		if len(order) >= capacity {
			evict := order[0]
			order = order[1:]
			delete(in, evict)
		}
		order = append(order, k)
		in[k] = true
	}
	return float64(hits) / float64(len(refs))
}

// hitRateLFU replays the stream through an LFU cache: on eviction, drop the resident
// key with the lowest access count. (Ties break by lowest key id — deterministic.)
func hitRateLFU(refs []int, capacity int) float64 {
	if capacity <= 0 {
		return 0
	}
	freq := make(map[int]int, capacity)
	in := make(map[int]bool, capacity)
	hits := 0
	for _, k := range refs {
		freq[k]++ // count every reference, resident or not
		if in[k] {
			hits++
			continue
		}
		if len(in) >= capacity {
			evictK, evictF := -1, 1<<30
			for x := range in {
				if freq[x] < evictF || (freq[x] == evictF && x < evictK) {
					evictF = freq[x]
					evictK = x
				}
			}
			delete(in, evictK)
		}
		in[k] = true
	}
	return float64(hits) / float64(len(refs))
}

// ===========================================================================
// Helpers
// ===========================================================================

func pct(v float64) string { return strconv.FormatFloat(v*100, 'f', 1, 64) + "%" }

// at returns the y value whose size entry equals (or is nearest below) the target — so
// the verdict reads the same swept curve the chart draws, not a re-run.
func at(sizes []int, ys []float64, target int) float64 {
	best, bestY := -1, 0.0
	for i, s := range sizes {
		if s <= target && s > best {
			best = s
			bestY = ys[i]
		}
	}
	if best < 0 && len(ys) > 0 {
		return ys[0]
	}
	return bestY
}

func esc(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;")
	return r.Replace(s)
}

// ===========================================================================
// Types
// ===========================================================================

// Trace is the generated access stream plus the workload that shaped it.
type Trace struct {
	Refs     []int
	Workload int
}

// Curves holds both policies' hit-rate over the swept cache sizes.
type Curves struct {
	Sizes    []int
	LRU      []float64
	LFU      []float64
	Workload int
}

// Chart draws the two hit-rate curves against cache size, with a size marker.
type Chart struct {
	Curves Curves
	Marker int
}

func (c Chart) Render() Rendered {
	cv := c.Curves
	const w, h, pad = 720.0, 400.0, 46.0
	plotW, plotH := w-2*pad, h-2*pad
	maxSize := universe
	sx := func(s int) float64 { return pad + float64(s)/float64(maxSize)*plotW }
	sy := func(v float64) float64 { return h - pad - v*plotH } // hit-rate 0..1

	var b strings.Builder
	fmt.Fprintf(&b, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %.0f %.0f">`, w, h)
	fmt.Fprintf(&b, `<rect width="%.0f" height="%.0f" fill="#fff"/>`, w, h)
	fmt.Fprintf(&b, `<rect x="%.0f" y="%.0f" width="%.0f" height="%.0f" fill="none" stroke="#e7ebf0"/>`,
		pad, pad, plotW, plotH)

	// y gridlines at 25/50/75/100%
	for _, g := range []float64{0.25, 0.5, 0.75, 1.0} {
		y := sy(g)
		fmt.Fprintf(&b, `<line x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f" stroke="#e7ebf0"/>`, pad, y, w-pad, y)
		fmt.Fprintf(&b, `<text x="%.1f" y="%.1f" font-family="sans-serif" font-size="10" fill="#5b6472">%.0f%%</text>`,
			pad-26, y+3, g*100)
	}

	// size marker (the selected cache size)
	mx := sx(c.Marker)
	fmt.Fprintf(&b, `<line x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f" stroke="#5b6472" stroke-dasharray="4 4"/>`,
		mx, pad, mx, h-pad)
	fmt.Fprintf(&b, `<text x="%.1f" y="%.1f" font-family="sans-serif" font-size="10" fill="#5b6472">size %d</text>`,
		mx+4, pad+12, c.Marker)

	line := func(sizes []int, ys []float64, color string) {
		var d strings.Builder
		for i := range sizes {
			verb := " L"
			if i == 0 {
				verb = "M"
			}
			fmt.Fprintf(&d, "%s%.1f %.1f", verb, sx(sizes[i]), sy(ys[i]))
		}
		fmt.Fprintf(&b, `<path d=%q fill="none" stroke=%q stroke-width="2.4"/>`, d.String(), color)
	}
	line(cv.Sizes, cv.LRU, "#2a78d6") // LRU
	line(cv.Sizes, cv.LFU, "#eda100") // LFU

	title := "working-set workload — recency, LRU should win"
	if cv.Workload == 1 {
		title = "Zipf workload — popularity, LFU should win"
	}
	fmt.Fprintf(&b, `<text x="%.0f" y="24" font-family="sans-serif" font-size="12" fill="#1b3a6b">hit-rate vs cache size — %s</text>`, pad, title)
	fmt.Fprintf(&b, `<text x="%.1f" y="%.1f" font-family="sans-serif" font-size="11" fill="#2a78d6">LRU</text>`, w-pad-70, pad+16)
	fmt.Fprintf(&b, `<text x="%.1f" y="%.1f" font-family="sans-serif" font-size="11" fill="#eda100">LFU</text>`, w-pad-34, pad+16)
	fmt.Fprintf(&b, `<text x="%.1f" y="%.1f" font-family="sans-serif" font-size="10" fill="#5b6472">cache size →</text>`, w-pad-84, h-pad+24)
	b.WriteString(`</svg>`)
	return Rendered{MIME: "image/svg+xml", Data: b.String()}
}

type Card struct{ Label, Value, Caption string }
type Readout struct{ Cards []Card }

// Render draws the verdict cards. A composite value with no Render method carries no
// MIME and the client hides the cell — so the cards render themselves. Engine-called,
// not a cell, so fmt here is fine.
func (r Readout) Render() Rendered {
	var b strings.Builder
	b.WriteString(`<div style="display:flex;gap:16px;flex-wrap:wrap">`)
	for _, c := range r.Cards {
		b.WriteString(`<div style="flex:1;min-width:150px;border:1px solid #e7ebf0;border-radius:8px;padding:12px 14px">`)
		fmt.Fprintf(&b, `<div style="font-size:12px;color:#5b6472">%s</div>`, esc(c.Label))
		fmt.Fprintf(&b, `<div style="font-size:22px;font-weight:700;color:#1b3a6b;margin:2px 0">%s</div>`, esc(c.Value))
		if c.Caption != "" {
			fmt.Fprintf(&b, `<div style="font-size:11px;color:#5b6472">%s</div>`, esc(c.Caption))
		}
		b.WriteString(`</div>`)
	}
	b.WriteString(`</div>`)
	return Rendered{MIME: "text/html", Data: b.String()}
}

type Rendered struct{ MIME, Data string }

type Markdown string

func (m Markdown) Render() Rendered { return Rendered{"text/markdown", string(m)} }
